
public class searchEmployee extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    Connection connection = null;
    Statement statement = null;
    ResultSet resultSet = null;
    String query;
    static int x = 0;
    int curRow = 0;
    DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

    public searchEmployee() {
        initComponents();

        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2,
                size.height / 2 - getHeight() / 2);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        panel1 = new java.awt.Panel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txt_tel = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        r_male = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        txt_dob = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_surname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_firstname = new javax.swing.JTextField();
        txt_id = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_add2 = new javax.swing.JTextField();
        txt_address = new javax.swing.JTextField();
        txt_salary = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txt_doj = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txt_status = new javax.swing.JTextField();
        txt_desig = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_dep = new javax.swing.JTextField();
        txt_job = new javax.swing.JTextField();
        cmd_delete = new javax.swing.JButton();
        txt_update = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txt_emp = new javax.swing.JLabel();
        empNo = new javax.swing.JLabel();
        empn = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        jCheckBox1.setText("jCheckBox1");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Adobe Arabic", 1, 14))); // NOI18N
        jPanel4.setLayout(null);

        jLabel11.setText("Employee ID :");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(16, 35, 67, 14);

        txt_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_searchMouseExited(evt);
            }
        });
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });
        jPanel4.add(txt_search);
        txt_search.setBounds(101, 32, 736, 20);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(10, 36, 0, 0);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Personal Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Adobe Arabic", 0, 18))); // NOI18N
        jPanel3.setLayout(null);

        jLabel7.setText("Contact :");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(16, 245, 45, 14);
        jPanel3.add(txt_tel);
        txt_tel.setBounds(142, 242, 168, 20);
        jPanel3.add(txt_email);
        txt_email.setBounds(142, 216, 168, 20);

        jLabel6.setText("Email :");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(16, 219, 31, 14);

        jLabel12.setText("Gender:");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(16, 158, 39, 14);

        r_male.setText("Male");
        r_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_maleActionPerformed(evt);
            }
        });
        jPanel3.add(r_male);
        r_male.setBounds(142, 154, 47, 23);

        jRadioButton2.setSelected(true);
        jRadioButton2.setText("Female");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton2);
        jRadioButton2.setBounds(189, 154, 59, 23);
        jPanel3.add(txt_dob);
        txt_dob.setBounds(142, 116, 177, 20);

        jLabel3.setText("Date of Birth :");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(16, 116, 68, 14);
        jPanel3.add(txt_surname);
        txt_surname.setBounds(142, 90, 177, 20);

        jLabel2.setText("Surname :");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(16, 93, 49, 14);

        jLabel1.setText("First name :");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(16, 67, 57, 14);

        txt_firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_firstnameActionPerformed(evt);
            }
        });
        jPanel3.add(txt_firstname);
        txt_firstname.setBounds(142, 64, 177, 20);

        txt_id.setEditable(false);
        jPanel3.add(txt_id);
        txt_id.setBounds(142, 37, 177, 20);

        jLabel8.setText("Address  ");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(16, 276, 45, 14);

        jLabel14.setText("Nationality");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(16, 302, 51, 14);
        jPanel3.add(txt_add2);
        txt_add2.setBounds(142, 299, 260, 20);
        jPanel3.add(txt_address);
        txt_address.setBounds(142, 273, 260, 20);

        txt_salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_salaryActionPerformed(evt);
            }
        });
        jPanel3.add(txt_salary);
        txt_salary.setBounds(430, 190, 160, 20);

        jLabel13.setText("Basic Salary :");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(340, 190, 70, 20);

        jLabel20.setText("Job Title :");
        jPanel3.add(jLabel20);
        jLabel20.setBounds(340, 160, 70, 20);
        jPanel3.add(txt_doj);
        txt_doj.setBounds(430, 100, 160, 20);

        jLabel19.setText("Date Hired :");
        jPanel3.add(jLabel19);
        jLabel19.setBounds(340, 100, 70, 20);

        jLabel18.setText("Date End");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(340, 130, 70, 20);
        jPanel3.add(txt_status);
        txt_status.setBounds(430, 130, 160, 20);
        jPanel3.add(txt_desig);
        txt_desig.setBounds(429, 63, 160, 20);

        jLabel17.setText("CivilId");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(337, 66, 60, 14);

        jLabel9.setText("Department :");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(337, 40, 80, 20);
        jPanel3.add(txt_dep);
        txt_dep.setBounds(429, 37, 160, 20);

        txt_job.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jobActionPerformed(evt);
            }
        });
        jPanel3.add(txt_job);
        txt_job.setBounds(430, 160, 160, 20);

        cmd_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete_16x16.gif"))); // NOI18N
        cmd_delete.setText("Delete Record");
        cmd_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_deleteActionPerformed(evt);
            }
        });
        jPanel3.add(cmd_delete);
        cmd_delete.setBounds(590, 264, 130, 50);

        txt_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update icon.png"))); // NOI18N
        txt_update.setText("Update Record");
        txt_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_updateActionPerformed(evt);
            }
        });
        jPanel3.add(txt_update);
        txt_update.setBounds(440, 264, 140, 50);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/erase-128.png"))); // NOI18N
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(510, 330, 140, 50);

        jLabel15.setText("Employee id :");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(16, 43, 64, 14);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(10, 126, 810, 496);

        txt_emp.setText("emp");
        getContentPane().add(txt_emp);
        txt_emp.setBounds(858, 8, 20, 14);

        empNo.setText("Enter Employee No");
        getContentPane().add(empNo);
        empNo.setBounds(10, 50, 110, 30);

        empn.setToolTipText("Enter employee no");
        getContentPane().add(empn);
        empn.setBounds(130, 50, 580, 30);

        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Search.png"))); // NOI18N
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search);
        search.setBounds(720, 40, 83, 50);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(867, 682));
        setLocationRelativeTo(null);
    }// </editor-fold>                        
       public void doConnect() {
        try {
            String URL = "jdbc:mysql://localhost:3306/employee";
            String username = "root";
            String password = "pi0551925228";
            connection = DriverManager.getConnection(URL, username, password);
            statement = connection.createStatement();

        } catch (SQLException ex) {
        }
    }
    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {                                       


    }                                      

    private void txt_jobActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void txt_salaryActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void txt_firstnameActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:

        gender = "Female";
    }                                             

    private void r_maleActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:

        gender = "Male";
    }                                      

    private void cmd_deleteActionPerformed(java.awt.event.ActionEvent evt) {                                           
        int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete record?", "Delete", JOptionPane.YES_NO_OPTION);
        if (p == 0) {

            String sql = "delete from employee where empid= " + Integer.parseInt(txt_search.getText());
            try {

                int x = statement.executeUpdate(sql);
                if (x == 1) {
                    String sql1 = "delete from empposition where empid= " + Integer.parseInt(txt_search.getText());
                    statement.executeUpdate(sql1);
                    JOptionPane.showMessageDialog(null, "Employee Deleted");

                }
            } catch (Exception e) {

                JOptionPane.showMessageDialog(null, e);
            }

        }


    }                                          

    private void txt_updateActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        LocalDate date1 = LocalDate.parse(txt_dob.getText());
        LocalDate date2 = LocalDate.parse(txt_doj.getText());
        LocalDate date3 = LocalDate.parse(txt_status.getText());
        int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to update?", "Update Record", JOptionPane.YES_NO_OPTION);
        if (p == 0) {
            try {
                doConnect();

                String vv = "update employee set civilNo = " + Integer.parseInt(txt_desig.getText()) + " , Name = ' " + txt_firstname.getText() + "' , Lnamr = '" + txt_surname.getText() + " ' , Nationalty = '" + txt_add2.getText() + "'\n"
                        + ", birthday = ' " + date1 + "' , address = ' " + txt_address.getText() + "' , maobile = '" + txt_tel.getText() + "' , basicsalary = " + Float.parseFloat(txt_salary.getText()) + " where empid= " + Integer.parseInt(empn.getText());;

                String vv1 = "update empposition set department = " + Integer.parseInt(txt_dep.getText()) + " , jobTitle = ' " + txt_job.getText() + "' , startjobdate = '" + date2 + " ' , endcontract = '" + date3 + "'\n"
                        + " where empid= " + Integer.parseInt(empn.getText());

                int r = statement.executeUpdate(vv);

                if (r == 1) {
                    statement.executeUpdate(vv1);
                    JOptionPane.showMessageDialog(this, "employee data updated sucssefully");
                } else {
                    JOptionPane.showMessageDialog(this, "faild update employee data");
                }
            } catch (SQLException ex) {
                Logger.getLogger(searchEmployee.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }                                          

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        txt_id.setText("");
        txt_firstname.setText("");
        txt_surname.setText("");
        txt_tel.setText("");
        txt_dob.setText("");
        txt_email.setText("");
        txt_address.setText("");
        txt_dep.setText("");
        txt_status.setText("");
        txt_salary.setText("");
        txt_add2.setText("");

        txt_desig.setText("");
        txt_job.setText("");

        txt_doj.setText("");

        txt_search.setText("");

    }                                        

    private void txt_searchMouseExited(java.awt.event.MouseEvent evt) {                                       

    }                                      

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {                                       
        doConnect();
        if (empn.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enetr employee Number");
        } else {
            try {

                String sql = "select * from employee INNER JOIN empposition on employee.empid=" + Integer.parseInt(empn.getText()) + " and empposition.empid= " + Integer.parseInt(empn.getText()) + ";";

                rs = statement.executeQuery(sql);

                if (rs.next() == true) {

                    txt_id.setText(rs.getString("empid"));

                    txt_firstname.setText(rs.getString("Name"));

                    txt_surname.setText(rs.getString("Lnamr"));

                    txt_dob.setText(rs.getString("birthday"));

                    // txt_email.setText(rs.getString("Email"));
                    txt_tel.setText(rs.getString("maobile"));

                    txt_address.setText(rs.getString("address"));

                    txt_dep.setText(rs.getString("department"));

                    txt_salary.setText(rs.getString("basicsalary"));

                    txt_add2.setText(rs.getString("Nationalty"));

                    txt_status.setText(rs.getString("endcontract"));

                    txt_doj.setText(rs.getString("startjobdate"));

                    txt_job.setText(rs.getString("jobTitle"));

                    txt_desig.setText(rs.getString("civilNo"));

                    byte[] img = rs.getBytes("Image");

                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Missing Data");
            }
        }
    }                                      

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(searchEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(searchEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(searchEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(searchEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new searchEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton cmd_delete;
    private javax.swing.JLabel empNo;
    private javax.swing.JTextField empn;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton2;
    private java.awt.Panel panel1;
    private javax.swing.JRadioButton r_male;
    private javax.swing.JButton search;
    private javax.swing.JTextField txt_add2;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_dep;
    private javax.swing.JTextField txt_desig;
    private javax.swing.JTextField txt_dob;
    private javax.swing.JTextField txt_doj;
    private javax.swing.JTextField txt_email;
    private javax.swing.JLabel txt_emp;
    private javax.swing.JTextField txt_firstname;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_job;
    private javax.swing.JTextField txt_salary;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_status;
    private javax.swing.JTextField txt_surname;
    private javax.swing.JTextField txt_tel;
    private javax.swing.JButton txt_update;
    // End of variables declaration                   

    //strin filename
    String filename = null;

    private String gender;

}

public class searchEmployee extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    Connection connection = null;
    Statement statement = null;
    ResultSet resultSet = null;
    String query;
    static int x = 0;
    int curRow = 0;
    DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

    public searchEmployee() {
        initComponents();

        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2,
                size.height / 2 - getHeight() / 2);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        panel1 = new java.awt.Panel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txt_tel = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        r_male = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        txt_dob = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_surname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_firstname = new javax.swing.JTextField();
        txt_id = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_add2 = new javax.swing.JTextField();
        txt_address = new javax.swing.JTextField();
        txt_salary = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txt_doj = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txt_status = new javax.swing.JTextField();
        txt_desig = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_dep = new javax.swing.JTextField();
        txt_job = new javax.swing.JTextField();
        cmd_delete = new javax.swing.JButton();
        txt_update = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txt_emp = new javax.swing.JLabel();
        empNo = new javax.swing.JLabel();
        empn = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        jCheckBox1.setText("jCheckBox1");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Adobe Arabic", 1, 14))); // NOI18N
        jPanel4.setLayout(null);

        jLabel11.setText("Employee ID :");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(16, 35, 67, 14);

        txt_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_searchMouseExited(evt);
            }
        });
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });
        jPanel4.add(txt_search);
        txt_search.setBounds(101, 32, 736, 20);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(10, 36, 0, 0);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Personal Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Adobe Arabic", 0, 18))); // NOI18N
        jPanel3.setLayout(null);

        jLabel7.setText("Contact :");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(16, 245, 45, 14);
        jPanel3.add(txt_tel);
        txt_tel.setBounds(142, 242, 168, 20);
        jPanel3.add(txt_email);
        txt_email.setBounds(142, 216, 168, 20);

        jLabel6.setText("Email :");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(16, 219, 31, 14);

        jLabel12.setText("Gender:");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(16, 158, 39, 14);

        r_male.setText("Male");
        r_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_maleActionPerformed(evt);
            }
        });
        jPanel3.add(r_male);
        r_male.setBounds(142, 154, 47, 23);

        jRadioButton2.setSelected(true);
        jRadioButton2.setText("Female");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton2);
        jRadioButton2.setBounds(189, 154, 59, 23);
        jPanel3.add(txt_dob);
        txt_dob.setBounds(142, 116, 177, 20);

        jLabel3.setText("Date of Birth :");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(16, 116, 68, 14);
        jPanel3.add(txt_surname);
        txt_surname.setBounds(142, 90, 177, 20);

        jLabel2.setText("Surname :");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(16, 93, 49, 14);

        jLabel1.setText("First name :");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(16, 67, 57, 14);

        txt_firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_firstnameActionPerformed(evt);
            }
        });
        jPanel3.add(txt_firstname);
        txt_firstname.setBounds(142, 64, 177, 20);

        txt_id.setEditable(false);
        jPanel3.add(txt_id);
        txt_id.setBounds(142, 37, 177, 20);

        jLabel8.setText("Address  ");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(16, 276, 45, 14);

        jLabel14.setText("Nationality");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(16, 302, 51, 14);
        jPanel3.add(txt_add2);
        txt_add2.setBounds(142, 299, 260, 20);
        jPanel3.add(txt_address);
        txt_address.setBounds(142, 273, 260, 20);

        txt_salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_salaryActionPerformed(evt);
            }
        });
        jPanel3.add(txt_salary);
        txt_salary.setBounds(430, 190, 160, 20);

        jLabel13.setText("Basic Salary :");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(340, 190, 70, 20);

        jLabel20.setText("Job Title :");
        jPanel3.add(jLabel20);
        jLabel20.setBounds(340, 160, 70, 20);
        jPanel3.add(txt_doj);
        txt_doj.setBounds(430, 100, 160, 20);

        jLabel19.setText("Date Hired :");
        jPanel3.add(jLabel19);
        jLabel19.setBounds(340, 100, 70, 20);

        jLabel18.setText("Date End");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(340, 130, 70, 20);
        jPanel3.add(txt_status);
        txt_status.setBounds(430, 130, 160, 20);
        jPanel3.add(txt_desig);
        txt_desig.setBounds(429, 63, 160, 20);

        jLabel17.setText("CivilId");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(337, 66, 60, 14);

        jLabel9.setText("Department :");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(337, 40, 80, 20);
        jPanel3.add(txt_dep);
        txt_dep.setBounds(429, 37, 160, 20);

        txt_job.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jobActionPerformed(evt);
            }
        });
        jPanel3.add(txt_job);
        txt_job.setBounds(430, 160, 160, 20);

        cmd_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete_16x16.gif"))); // NOI18N
        cmd_delete.setText("Delete Record");
        cmd_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_deleteActionPerformed(evt);
            }
        });
        jPanel3.add(cmd_delete);
        cmd_delete.setBounds(590, 264, 130, 50);

        txt_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update icon.png"))); // NOI18N
        txt_update.setText("Update Record");
        txt_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_updateActionPerformed(evt);
            }
        });
        jPanel3.add(txt_update);
        txt_update.setBounds(440, 264, 140, 50);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/erase-128.png"))); // NOI18N
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(510, 330, 140, 50);

        jLabel15.setText("Employee id :");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(16, 43, 64, 14);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(10, 126, 810, 496);

        txt_emp.setText("emp");
        getContentPane().add(txt_emp);
        txt_emp.setBounds(858, 8, 20, 14);

        empNo.setText("Enter Employee No");
        getContentPane().add(empNo);
        empNo.setBounds(10, 50, 110, 30);

        empn.setToolTipText("Enter employee no");
        getContentPane().add(empn);
        empn.setBounds(130, 50, 580, 30);

        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Search.png"))); // NOI18N
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search);
        search.setBounds(720, 40, 83, 50);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(867, 682));
        setLocationRelativeTo(null);
    }// </editor-fold>                        
       public void doConnect() {
        try {
            String URL = "jdbc:mysql://localhost:3306/employee";
            String username = "root";
            String password = "pi0551925228";
            connection = DriverManager.getConnection(URL, username, password);
            statement = connection.createStatement();

        } catch (SQLException ex) {
        }
    }
    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {                                       


    }                                      

    private void txt_jobActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void txt_salaryActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void txt_firstnameActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:

        gender = "Female";
    }                                             

    private void r_maleActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:

        gender = "Male";
    }                                      

    private void cmd_deleteActionPerformed(java.awt.event.ActionEvent evt) {                                           
        int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete record?", "Delete", JOptionPane.YES_NO_OPTION);
        if (p == 0) {

            String sql = "delete from employee where empid= " + Integer.parseInt(txt_search.getText());
            try {

                int x = statement.executeUpdate(sql);
                if (x == 1) {
                    String sql1 = "delete from empposition where empid= " + Integer.parseInt(txt_search.getText());
                    statement.executeUpdate(sql1);
                    JOptionPane.showMessageDialog(null, "Employee Deleted");

                }
            } catch (Exception e) {

                JOptionPane.showMessageDialog(null, e);
            }

        }


    }                                          

    private void txt_updateActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        LocalDate date1 = LocalDate.parse(txt_dob.getText());
        LocalDate date2 = LocalDate.parse(txt_doj.getText());
        LocalDate date3 = LocalDate.parse(txt_status.getText());
        int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to update?", "Update Record", JOptionPane.YES_NO_OPTION);
        if (p == 0) {
            try {
                doConnect();

                String vv = "update employee set civilNo = " + Integer.parseInt(txt_desig.getText()) + " , Name = ' " + txt_firstname.getText() + "' , Lnamr = '" + txt_surname.getText() + " ' , Nationalty = '" + txt_add2.getText() + "'\n"
                        + ", birthday = ' " + date1 + "' , address = ' " + txt_address.getText() + "' , maobile = '" + txt_tel.getText() + "' , basicsalary = " + Float.parseFloat(txt_salary.getText()) + " where empid= " + Integer.parseInt(empn.getText());;

                String vv1 = "update empposition set department = " + Integer.parseInt(txt_dep.getText()) + " , jobTitle = ' " + txt_job.getText() + "' , startjobdate = '" + date2 + " ' , endcontract = '" + date3 + "'\n"
                        + " where empid= " + Integer.parseInt(empn.getText());

                int r = statement.executeUpdate(vv);

                if (r == 1) {
                    statement.executeUpdate(vv1);
                    JOptionPane.showMessageDialog(this, "employee data updated sucssefully");
                } else {
                    JOptionPane.showMessageDialog(this, "faild update employee data");
                }
            } catch (SQLException ex) {
                Logger.getLogger(searchEmployee.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }                                          

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        txt_id.setText("");
        txt_firstname.setText("");
        txt_surname.setText("");
        txt_tel.setText("");
        txt_dob.setText("");
        txt_email.setText("");
        txt_address.setText("");
        txt_dep.setText("");
        txt_status.setText("");
        txt_salary.setText("");
        txt_add2.setText("");

        txt_desig.setText("");
        txt_job.setText("");

        txt_doj.setText("");

        txt_search.setText("");

    }                                        

    private void txt_searchMouseExited(java.awt.event.MouseEvent evt) {                                       

    }                                      

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {                                       
        doConnect();
        if (empn.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enetr employee Number");
        } else {
            try {

                String sql = "select * from employee INNER JOIN empposition on employee.empid=" + Integer.parseInt(empn.getText()) + " and empposition.empid= " + Integer.parseInt(empn.getText()) + ";";

                rs = statement.executeQuery(sql);

                if (rs.next() == true) {

                    txt_id.setText(rs.getString("empid"));

                    txt_firstname.setText(rs.getString("Name"));

                    txt_surname.setText(rs.getString("Lnamr"));

                    txt_dob.setText(rs.getString("birthday"));

                    // txt_email.setText(rs.getString("Email"));
                    txt_tel.setText(rs.getString("maobile"));

                    txt_address.setText(rs.getString("address"));

                    txt_dep.setText(rs.getString("department"));

                    txt_salary.setText(rs.getString("basicsalary"));

                    txt_add2.setText(rs.getString("Nationalty"));

                    txt_status.setText(rs.getString("endcontract"));

                    txt_doj.setText(rs.getString("startjobdate"));

                    txt_job.setText(rs.getString("jobTitle"));

                    txt_desig.setText(rs.getString("civilNo"));

                    byte[] img = rs.getBytes("Image");

                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Missing Data");
            }
        }
    }                                      

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(searchEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(searchEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(searchEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(searchEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new searchEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton cmd_delete;
    private javax.swing.JLabel empNo;
    private javax.swing.JTextField empn;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton2;
    private java.awt.Panel panel1;
    private javax.swing.JRadioButton r_male;
    private javax.swing.JButton search;
    private javax.swing.JTextField txt_add2;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_dep;
    private javax.swing.JTextField txt_desig;
    private javax.swing.JTextField txt_dob;
    private javax.swing.JTextField txt_doj;
    private javax.swing.JTextField txt_email;
    private javax.swing.JLabel txt_emp;
    private javax.swing.JTextField txt_firstname;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_job;
    private javax.swing.JTextField txt_salary;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_status;
    private javax.swing.JTextField txt_surname;
    private javax.swing.JTextField txt_tel;
    private javax.swing.JButton txt_update;
    // End of variables declaration                   

    //strin filename
    String filename = null;

    private String gender;

}
